### PR TITLE
fixes #523

### LINKED ISSUE #523: Documentation📄: Open Horizon text in top left nav is too dark
### What is the current documentation state?

Request to make it lighter, for daytime mode.

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

_No response_

### LINKED ISSUE #525: Documentation📄: Add LF Edge reference to documentation site
### What is the current documentation state?

Add a new line in the footer file reading:

Open Horizon is a [Stage Two project](https://wiki.lfedge.org/display/LE/Stage+2%3A+Growth) at [LF Edge](https://www.lfedge.org/).

This will need to be added to the `_config.yml` file at the end of the `footer_content` property value.  You will need to convert the above to HTML and backslash escape any quote marks.

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by dotarjun**
# Pull Request Template

Fixes # 523
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

guration

## Additional Context (Please include any Screenshots/gifs if relevant)
image

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by dotarjun** [comment]
@joewxboy

**Review by johnwalicki — APPROVED** [review]
Fantastic

**Comment by johnwalicki** [comment]
This commit fixes #523
Not #525

**Comment by johnwalicki** [comment]
I recommend a rewrite of the commit message so that it follows the Open Horizon convention.

**Comment by dotarjun** [comment]
> This commit fixes #523 Not #525

my bad. I have fixed the commit message

**Comment by johnwalicki** [comment]
Better! Thanks.  Can you rewrite the git commit message to be
`Issue #523 - style: fix navbar text color`

**Review by joewxboy — APPROVED** [review]

**Pull request merged**
