### PR TITLE
Issue-238: Added Support for Ubuntu 22.04 Jammy

### LINKED ISSUE #238: Documentation📄: Support for Ubuntu 22.04 Jammy
### What is the current documentation state?

@dlarson04 has merged support for Ubuntu 22.04  aka Jammy Jellyfish
https://github.com/open-horizon/anax/issues/3157

We should update the following docs to include `jammy`
- installing/adding_devices.md

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by YashKamboj**
Signed-off-by: Yash Kamboj <yashkamboj29@gmail.com>

# Pull Request Template

## Description 
 Added Support for Ubuntu 22.04 Jammy

Fixes #238  (issue)

### CODE REVIEW

**Review by johnwalicki — CHANGES_REQUESTED** [review]
Please move this to the beginning of the list of supported Ubuntu versions `Ubuntu 22.x (jammy),`

**Comment by YashKamboj** [comment]
@johnwalicki Done!!!

**Review by Abhijay007 — APPROVED** [review]
LGTM

**Review by joewxboy — APPROVED** [review]

**Comment by joewxboy** [comment]
@johnwalicki It looks like GitHub Is waiting for you to resolve before we can merge.

**Review by johnwalicki — APPROVED** [review]

**Pull request merged**
