### PR TITLE
chore : added contributors in readme

### LINKED ISSUE #209: Added All Contributors in Readme
Adding all Contributors in one place in the project

### PR DESCRIPTION
**Pull request by Ayush7614**
Fixes #209 

This PR Contains
* Added Contributors in Readme

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @johnwalicki

**Comment by Ayush7614** [comment]
image
Output

**Review by Abhijay007 — APPROVED** [review]
LGTM !!

**Comment by johnwalicki** [comment]
Maybe more emojiis than my particular tastes but Ok. Merging.

**Pull request merged**
