### PR TITLE
Added link to open horizon website

### LINKED ISSUE #256: Documentation📄: README doesn't link to open-horizon.github.io
### What is the current documentation state?

The https://github.com/open-horizon/open-horizon.github.io repo README.md does not contain a link to the actual Open Horizon Web Site [open-horizon.github.io/](https://open-horizon.github.io/)

Add a sentence / link to the README in the first paragraph.

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #256 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by PrajwalBorkar** [comment]
> Thanks for the contribution / commit / PR !
> 
> Just adding a link in the header is maybe a bit too subtle.
> 
> I imagined adding a sentence in the first paragraph. `To visit this Open Horizon documentation site visit [open-horizon.github.io](open-horizon.github.io/)`

I made changes as you said please check :)

**Review by Abhijay007 — COMMENTED** [review]
LGTM 
Just DCO left, please sign that :)

**Comment by PrajwalBorkar** [comment]
> LGTM Just DCO left, please sign that :)

Should I add that in commit message? Im unaware of this.

**Comment by Abhijay007** [comment]
> > LGTM Just DCO left, please sign that :)
> 
> Should I add that in commit message? Im unaware of this.

you can follow the steps by clicking on the "details"

image

**Comment by PrajwalBorkar** [comment]
> > > LGTM Just DCO left, please sign that :)
> > 
> > 
> > Should I add that in commit message? Im unaware of this.
> 
> you can follow the steps by clicking on the "details" in the checks/workflow/test section
> 
> image

Actually I don't have local copy of repo in my machine any other option?

**Comment by johnwalicki** [comment]
StackOverflow has an answer for everything - https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits
```
git clone git@github.com:PrajwalBorkar/open-horizon.github.io.git
git rebase --signoff HEAD~2
git push origin master
```

**Comment by PrajwalBorkar** [comment]
> StackOverflow has an answer for everything - https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits
> 
> ```
> git clone git@github.com:PrajwalBorkar/open-horizon.github.io.git
> git rebase --signoff HEAD~2
> git push origin master
> ```

Thanks for the help. Implemented the changes 👍

**Review by johnwalicki — APPROVED** [review]

**Comment by johnwalicki** [comment]
Merged! Thanks

**Comment by PrajwalBorkar** [comment]
> The URL is incorrect. It expands to `https://github.com/open-horizon/open-horizon.github.io/blob/master/open-horizon.github.io` and fails with a 404 error.
> 
> The correct URL should have been `visit [open-horizon.github.io](https://open-horizon.github.io/)`

Should I change the URL now it is merged I think.

**Pull request merged**
