### PR TITLE
Issue #333: Fix broken link for agent-install in anax doc

### LINKED ISSUE #333: Website Contains Broken Links
## Website Contains Broken Links

Broken Link Checker found :coffin: links on https://open-horizon.github.io/

[View Results](https://github.com/open-horizon/open-horizon.github.io/actions/runs/3163048962?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by dipesh-rawat**
# Pull Request Template

## Description

Fix broken link related to the agent install in the anax documentation. The fix involves providing a hard link to the missing page.

Fixes #333 (partial)

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## How Has This Been Tested?

Visit

1. https://open-horizon.github.io/docs/anax/docs/node_management.html
2. Click on the link in configuration under the 'Agent Auto Upgrade' section to open https://github.com/open-horizon/anax/blob/master/agent-install/README.md#configuration-file

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@johnwalicki Could you please review this PR?

**Review by johnwalicki — COMMENTED** [review]
This will get overwritten the next time there is a change in the anax repo docs tree. The copydocs  GHA will copy docs files from the anax repo to this repo.  The correct way to fix the broken link is in the anax repo.

**Comment by johnwalicki** [comment]
This will get overwritten the next time there is a change in the anax repo docs tree. The copydocs  GHA will copy docs files from the anax repo to this repo.  The correct way to fix the broken link is in the anax repo.

**Comment by johnwalicki** [comment]
Closing this PR

**Comment by johnwalicki** [comment]
I can investigate tomorrow.

**Pull request closed without merging**
