### PR TITLE
Removed nl folder

### LINKED ISSUE #125: Remove NL folders in doc repo
At this time, OH doc content is not translated (11/2021), but the IEAM content is. Because of this, the NL folder were copied to the OH repo when it was originally created. But the NL folders serve no purpose in OH at this time, so they can be removed for now.

### PR DESCRIPTION
**Pull request by Akshit42-hue**
Signed-off-by: Axit Patel patelakshit2025@gmail.com

Fixes #125 
Do let me know if any change is required

### CODE REVIEW

**Comment by Rene-Ch1** [comment]
Hi, I think that this update is fine. Can you assign me as a reviewer? I think that someone needs to be an assigned reviewer in order to officially approve the PR. Thank you!!

**Comment by Akshit42-hue** [comment]
Can you please guide me how to assign as a reviewer

**Comment by Rene-Ch1** [comment]
@Akshit42-hue Hi, in the upper right-hand side of the issue page is a selectable field named Reviewer:

image

Click on the word Reviewer, type in a name (the field will try to auto-fill based on your keystrokes). Click on the person or persons you want to add.

**Comment by joewxboy** [comment]
@Akshit42-hue I added Rene and myself.  Interesting problem ... a first-time submitter can't add a reviewer.  We'll have to look into that.

**Comment by Akshit42-hue** [comment]
Thanks for helping me out @Rene-Ch1 @joewxboy

**Comment by joewxboy** [comment]
@Akshit42-hue while we review the changes, was your commit signed-off?  See https://open-horizon.github.io/common-requests/contribute.html

And if it wasn't clear that you needed to do that on every commit, can you give us advice on where we could post that information for first-time committers?  Thanks. :)

**Comment by Akshit42-hue** [comment]
Yes I have actually Signed-off my commit 
openhorizon

**Comment by joewxboy** [comment]
Ahh, thanks for clarifying.  You _signed_ your commit, but didn't _sign-off_ your commit.  Those are two different things.  If you take a look at your commit https://github.com/open-horizon/open-horizon.github.io/pull/132/commits/8b80a19e8211d5a1e1f357c504eb60b52f90a321 you can see the title (second title on the page) has a red X beside it.  If you amend your commit, you can add it.  

When initially committing, use the `-s` or `--signoff` flag.  When amending an existing commit, try:
```
git commit --amend --signoff
git push -f
```

**Comment by Akshit42-hue** [comment]
Ohh ! Just working on sign-off

**Comment by Akshit42-hue** [comment]
Can I make new PR ? @joewxboy

**Pull request closed without merging**
