### PR TITLE
Issue-175 (chore) : Added a linter for the docs

### LINKED ISSUE #175: Feature Request: Add a linter for the docs
### Is your feature request related to a problem? Please describe.

I observed that we are merging a lot of faulty PRs(broken links, garbage data in README) due to manual reviews. Linting will help us in reviewing new PRs and there are other benefits.

Linters help in SEO optimisations, checking broken links and following industry standards that helps a lot.

### Describe the solution you'd like.

Add a GHA linter for docs repo, that runs on each Pull request and also add steps in contributing guide to locally test the code through linter.

### Describe alternatives you've considered

_No response_

### Additional context.

https://github.com/p5py/p5/pull/268
I had implemented a linter once and it helped us a lot in identifying the errors beforehand.

### PR DESCRIPTION
**Pull request by Abhijay007**
# Pull Request Template

## Description

Added a linter for the docs

Fixes #175 

## Type of change

code 

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

testing in progress 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by johnwalicki** [comment]
What options can be tweaked in the `my_markdownlint.yml` file?

**Comment by Abhijay007** [comment]
> What options can be tweaked in the `my_markdownlint.yml` file?

I think there are not many options 😅 as there using the pre-built action but we can exclude and include the files, you can read about this action here :  https://github.com/marketplace/actions/my-markdown-linter

**Comment by johnwalicki** [comment]
There are lots and lots of linter errors caused by
```
  '''
  sudo some command
  '''
   {: codeblock}


## Header with an anchor
{: #ppc64le-machines}
```

**Comment by Abhijay007** [comment]
@johnwalicki, @joewxboy can you please tell me which files to include and exclude from the list, and one more thing I got a mail regarding the invalid YAML syntax in this PR, I re-checked this file couple of times but was not able to find any syntax error in line 11 (as mentioned by the report), can you please look into this too :)

**Comment by johnwalicki** [comment]
>  I got a mail regarding the invalid YAML syntax in this PR, I re-checked this file couple of times but was not able to find any syntax error in line 11 (as mentioned by the report), can you please look into this too :)

I pasted the yaml into http://www.yamllint.com/
It reported this error
` (<unknown>): mapping values are not allowed in this context at line 11 column 12 `

**Review by Rene-Ch1 — APPROVED** [review]

**Pull request closed without merging**
