### PR TITLE
Issue-151: Changing Titles and Adding Description

### LINKED ISSUE #151: Feature Request: Change Pages Title and Add feedback option
### Is your feature request related to a problem? Please describe.

Most of the pages in the Open Horizon Website has title"Open Horizon". So, I want to add related title wrt. page content. Like [this](https://open-horizon.github.io/docs/getting_started/overview_oh.html) page title should "Overview- Open Horizon".

Add Feedback Option in the page as discusssed [here](https://github.com/open-horizon/open-horizon.github.io/issues/142#issuecomment-1040814356) .

### PR DESCRIPTION
**Pull request by Sukriti-sood**
Fixes #151 

This pr is one of the addition to fix linked issue.

I would like feedback on whether I am making the right changes.

@joewxboy

### CODE REVIEW

**Comment by joewxboy** [comment]
Some minor feedback while I review:

1. Let's prefix the title of the PR with the issue number in the form: `Issue-151: ` and then the rest of the title.  Some of our systems expect this naming convention.
2. Ensure that you link the Issue to the PR.  <-- Looks like this is now linked.

**Review by joewxboy — CHANGES_REQUESTED** [review]
Thanks.

Can you please describe what the CSS and className changes accomplish?  This will help assist us in understanding the results.  I can see that the changes were made in the proper locations in order to effect every page on the site (thank you, and it illustrates your understanding of the site structure in Jekyll), but I'm not sure what it was intended to correct.

Also, please fix the PR title. :)

**Comment by Sukriti-sood** [comment]
@

> Some minor feedback while I review:
> 
> 1. Let's prefix the title of the PR with the issue number in the form: `Issue-151: ` and then the rest of the title.  Some of our systems expect this naming convention.
> 2. Ensure that you link the Issue to the PR.  <-- Looks like this is now linked.

Sorry for violating the rule.

**Comment by joewxboy** [comment]
> Sorry for violating the rule.

It's more of a convention. :). I think the project has done a poor job so far of capturing all of these in one place, which makes it difficult for new contributors to learn all of them except by inference and intuition.

**Comment by Sukriti-sood** [comment]
The @joewxboy heading section had lots of extra padding and which is depicting sort of bad UI. You can test and look at the changes ... or I will share some of the screenshots in some time

**Review by joewxboy — APPROVED** [review]
Thank you.

**Pull request merged**
