### PR TITLE
Issue #359 - Updates to Docs main index.html

### LINKED ISSUE #359: Orphan Pages
## Orphan pages

Orphan pages :coffin: found on https://open-horizon.github.io/

[View Results](https://github.com/open-horizon/open-horizon.github.io/actions/runs/3588947661?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by johnwalicki**
Signed-off-by: John Walicki <johnwalicki@gmail.com>

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #359  #352 #215 #351

## Type of change

- [x] This change requires a documentation update

## How Has This Been Tested?

Visit https://open-horizon.github.io/docs/

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by johnwalicki** [comment]
I rolled in issue #352 and added a link to the Supported Arch/OS page

**Comment by johnwalicki** [comment]
I updated the index.html to also link to the MMS docs - reported in #215

**Comment by johnwalicki** [comment]
There were 5 cards on the Index page. It was unbalanced (One row of three  cards and one row of two cards)
The bottom sections about Help - FAQ, Troubleshooting, Support took up lots of web page space.  I collapsed those links into a "Help and Support" card.  Now the webpage is balanced with 2 rows of three cards.

**Comment by johnwalicki** [comment]
I used the newly freed up space at the bottom of the page to include a statement / link about the Open Horizon responsible security disclosure procedure.  We wanted to add this per #351

**Comment by johnwalicki** [comment]
@joewxboy  Please Review.  I've made updates all of the index page.  I'm going to stop here.  It looks ok on my local testing but I to see it live.

**Comment by johnwalicki** [comment]
I've fiddled with the <div></div> on the index.html so that they match.  I think...

**Review by joewxboy — APPROVED** [review]
Thanks for also adding instructions for security reporting.

**Comment by joewxboy** [comment]
@johnwalicki It's not serious, but the page has some funny layout wrapping for me.  I have not yet loaded it on a cellphone to view it there.

**Comment by johnwalicki** [comment]
@joewxboy  Thanks for the review and merge.  I, too, see the cards are not well aligned.  I think the "Review supported architectures and operating systems" is too long and causing the poor card wrapping.  I'll submit another Issue / PR to fix it up.

**Pull request merged**
