### PR TITLE
CI :Added Pull Request, Issue Templates, GHA

### PR DESCRIPTION
**Pull request by Ayush7614**
Signed-off-by: Ayush Kumar [ayushknj3@gmail.com](mailto:ayushknj3@gmail.com)

This PR:

* Adds Prosebot (Automated Grammar/Spell and consistency checks) it is for Docs and Readme 
* Adds Issue Templates Others.md
* Adds GHA config yml for first timer issues
* Adds PR Templates (there is no PR template in the Repo)

cc @joewxboy

### CODE REVIEW

**Comment by joewxboy** [comment]
@Ayush7614 It looks like there is some overlap with https://github.com/open-horizon/open-horizon.github.io/pull/133

But you have some good ideas in here.

Maybe if you remove the feature request and documentation update templates, we'd remove the overlap.

FYI ... It's also a good practice for each PR to be based on one or more open issues.  Could I get you to open an issue for the remaining items and then link this PR to that issue?

**Comment by Ayush7614** [comment]
> @Ayush7614 It looks like there is some overlap with #133
> 
> But you have some good ideas in here.
> 
> Maybe if you remove the feature request and documentation update templates, we'd remove the overlap.
> 
> FYI ... It's also a good practice for each PR to be based on one or more open issues. Could I get you to open an issue for the remaining items and then link this PR to that issue?

cc @joewxboy now you can review no i am not open any issue you can link the PR

**Review by joewxboy — APPROVED** [review]
Looks good, thanks.  When is the spell checker triggered?  Is it done manually or in response to a specific event?

**Comment by Ayush7614** [comment]
> Looks good, thanks. When is the spell checker triggered? Is it done manually or in response to a specific event?

It is response automatic whenever there is some docs file markdown files or changes in README or docs it can automatic response just like GHA(Github Actions) It is also same as Github Actions

**Comment by Ayush7614** [comment]
cc @joewxboy

**Pull request merged**
