### PR TITLE
Issue-166 (Chore): Updated Technical Support Page

### LINKED ISSUE #166: Documentation📄: Update Technical Support Page
### What is the current documentation state?

Update "slack" links in the technical support page as it is not redirected to anywhere and open-horizon has shifted their platform to elements for internal communication purposes.

### Where is this stated?

you can access this page from [here](https://open-horizon.github.io/common-requests/get-technical-support.html)

### Why do you want to improve the statement?

it is important links as it is required by new and existing contributors for reaching out to the community and engaging with them to ask their doubts and sharing suggestions as well. 

### Proposed Statement

Replace these links with: https://chat.lfx.linuxfoundation.org/

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

## Description

updated slack links to "Element" on the technical support page

Fixes #166

## Type of change

code

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

locally by running it on the server

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Abhijay007** [comment]
@unnati914, @joewxboy please review this PR :)

**Review by joewxboy — CHANGES_REQUESTED** [review]
Instead of "Element Room" you can say "chat room".

Also, the external links are missing the external link css class: `{: .externalLink}`

**Comment by joewxboy** [comment]
> But I thought we don't need that tiny arrow here 😅 as it was not present initially, but no problem, will add that :)
> […](#)

Principle of least surprise.  Since this link opens in a new window or tab, we might as well "warn" them in advance.

**Comment by Abhijay007** [comment]
Okay got it, I will keep that in mind for future contributions :)

**Review by joewxboy — APPROVED** [review]

**Pull request merged**
