### PR TITLE
Issue-297: Added link to anax from docs index page to prevent orphan …

### LINKED ISSUE #297: Orphan Pages
## Orphan pages

Orphan pages :coffin: found on https://open-horizon.github.io/

[View Results](https://github.com/open-horizon/open-horizon.github.io/actions/runs/2772045839?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by joewxboy**
…pages

Signed-off-by: Joe Pearson <joewxboy@users.noreply.github.com>

# Pull Request Template

## Description

Added a link to the anax docs.

Fixes #297 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Review by johnwalicki — CHANGES_REQUESTED** [review]
Can you modify the date to 2022-08-09

**Comment by joewxboy** [comment]
@johnwalicki If you could review ... this removed legacy XHTML markup from the index page (turns it into HTML5 markup) and adds the link to the anax docs section.

**Review by johnwalicki — CHANGES_REQUESTED** [review]
Can you modify the date to 2022 ?

**Comment by joewxboy** [comment]
@johnwalicki OK, updated the date year.

**Pull request merged**
