### PR TITLE
added lighthouse ci

### PR DESCRIPTION
**Pull request by Ayush7614**
This PR Contains

- Added Lighthouse CI for tracking website performance

- 
screenshot-github com-2022 06 04-20_51_04

Working Like This

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @joewxboy

**Review by Abhijay007 — COMMENTED** [review]
@Ayush7614 instead of scheduling this GHA can we edit this in a way that it will show us data after a particular pr or can we run this workflow on the PRs themselves? as it will be great if we get data on every PR and how that particular PR gonna affect the performance and other parameters of the site.

**Comment by Ayush7614** [comment]
> @Ayush7614 instead of scheduling this GHA can we edit this in a way that it will show us data after a particular pr or can we run this workflow on the PRs themselves? as it will be great if we get data on every PR and how that particular PR gonna affect the performance and other parameters of the site.

 this will run on particular PR themselves if any PR is opened then this Gha is running

**Review by joewxboy — APPROVED** [review]
Is it possible to make a short video demonstrating how to manually run it, where the report shows up in a PR, and what the ratings mean?  I'm thinking about two minutes long, if possible.  If that interests you, please let us know in the documentation working group chat.  Glen or I can then add official Open Horizon bumpers to the beginning and end, and get it posted to our Open Horizon YouTube playlist if you'd like.

**Comment by joewxboy** [comment]
> > @Ayush7614 instead of scheduling this GHA can we edit this in a way that it will show us data after a particular pr or can we run this workflow on the PRs themselves? as it will be great if we get data on every PR and how that particular PR gonna affect the performance and other parameters of the site.
> 
> this will run on particular PR themselves if any PR is opened then this Gha is running

@Abhijay007 Are you OK with this as it is?  Let me know so I can merge it, or request that @Ayush7614 make additional changes.  Thanks.

**Comment by Ayush7614** [comment]
There is no additional changes @joewxboy This is passing so you can merge it.

**Pull request merged**
