### PR TITLE
Issue 338 - fixed hyperlink format

### PR DESCRIPTION
**Pull request by marhabac33**
Signed-off-by: Marhababanu Chariwala <marhabac33@gmail.com>

# Pull Request Template

## Description

Fixed the hyperlink format to markdown. 

Fixes https://github.com/open-horizon/open-horizon.github.io/issues/338

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Manually verification

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by marhabac33** [comment]
@joewxboy please let me know if anything else is need to running the workflows

**Comment by joewxboy** [comment]
Congratulations, @marhabac33 you are now officially a project Contributor.
FYI @johnwalicki

**Comment by marhabac33** [comment]
Woohoo 💃🏽 
Thanks @joewxboy

**Comment by johnwalicki** [comment]
This fix will be overwritten the next time the page is updated over in the devops repo.
https://github.com/open-horizon/devops/blob/master/docs/index.md

That's where this fix should go.

**Comment by marhabac33** [comment]
@johnwalicki oh so any changes to the content should be done via appropriate repo docs. And  `open-horizon.github.io` just get the latest content from there? Did I understand it correctly?

I can open an issue in https://github.com/open-horizon/devops/ and deliver the changes there. I hope it wont cause any conflicts. Let me know if I should go ahead. 

cc: @joewxboy

**Comment by joewxboy** [comment]
@marhabac33 Yes, please

**Comment by johnwalicki** [comment]
@joewxboy - Thanks for noticing this.  A month ago, I fixed a bunch of these anchor tags in that devops All-in-One Management Hub page.  I must have missed that one.

@marhabac33 - Thanks for pursuing the fix over in the devops repo.    There is a CopyDocs GitHub Action which will trigger on a PR merge and the file will be copied over to the `open-horizon.github.io` repo.

**Pull request merged**
