### PR TITLE
added codeql gha for code analysis

### PR DESCRIPTION
**Pull request by Ayush7614**
This PR Contains

- Added Codeql Gha for Code Analysis

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @Abhijay007 @joewxboy

**Comment by johnwalicki** [comment]
There is very little / no source code in the docs repo.  Is this needed?

**Comment by Ayush7614** [comment]
> There is very little / no source code in the docs repo. Is this needed?

Yes it is needed because here Ruby and JS is used and the code is little but the code is there that`s why i open this one please review it and merge it

**Review by johnwalicki — APPROVED** [review]
Nice to have. Not critical. It throws a bunch of warnings.

**Pull request merged**
