### PR TITLE
Issue #432 - fix lint warnings

### LINKED ISSUE #432: Documentation📄: Fix lint warnings
### What is the current documentation state?

As discussed in #175  there are only a few pages remaining in this docs repo that have obvious lint errors.

This issue will fix some lint / formatting warnings

- docs/admin/accessing_logs.md
- docs/installing/fdo.md
- docs/installing/watson_speech.md
- docs/troubleshoot/troubleshooting.md
- docs/user_management/gdpr.md
- docs/using_edge_services/cpu_load_example.md
- docs/using_edge_services/using_patterns.md

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by johnwalicki**
# Pull Request Template

Fixes #432 
- fix Lint warnings

## Type of change

- [x] This change requires a documentation update

## Checklist:

- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Review by joewxboy — APPROVED** [review]
Does this directive do anything?

{: codeblock}

I used to use it at the end of a code block because the "copy to clipboard" function that I used required it.  I believe the new Jekyll template no longer requires it.  Is it being used downstream or for a purpose of which I am unaware?

**Comment by johnwalicki** [comment]
@joewxboy I don't know the providence of the `{: codeblock}` directive. I think Rene uses it downstream?

**Comment by johnwalicki** [comment]
@joewxboy  - Yes, I confirmed.  The downstream documentation requires the `{: codeblock}` directive to show the Copy to Clipboard icon.  I found a downstream page where the directive is missing from a code block - and that section does not have a Copy to Clipboard icon.

**Comment by joewxboy** [comment]
Thanks.  I'll add to Best Practices.

**Pull request merged**
