### PR TITLE
CI : Added Greetbot, Stalebot, and Requestbot

### LINKED ISSUE #138: Add GitHub Bots to Open-Horizon Repositories
We need to have project-specific bots later (Especially for Go, Python, and JS-based projects) to track code quality, builds and all. Please have a look and let me know what you think. You can also add more bot integrations that we can have right here.

This issue would be used to track the integration of GitHub Bots across Open-Horizon repositories.

1 . Stale Bot  [Integration](https://github.com/apps/stale)
* Closes Issues and Pull Requests if not attended to in a specified period of time
* Maintains the overall sanctity of the issues and Pull Requests tab.
*  Keeps a check on spam/unnecessary Issues and PRs.

2 . Greet Bot [Integration](https://github.com/actions/first-interaction)
* Greet First Time Contributors

3 . Request - Info [Integration](https://github.com/apps/request-info)
* Request for the information if the issues/PR Content body is empty
*  Help us in Spam / invalid issues and PRs

We can also add many bots i have more specific bots and i can also add in the future
What is the idea cc @joewxboy  ?

### PR DESCRIPTION
**Pull request by Ayush7614**
Signed-off-by: Ayush Kumar [ayushknj3@gmail.com](mailto:ayushknj3@gmail.com)

This PR:

1 . Stale Bot  [Integration](https://github.com/apps/stale)
* Closes Issues and Pull Requests if not attended to in a specified period of time
* Maintains the overall sanctity of the issues and Pull Requests tab.
*  Keeps a check on spam/unnecessary Issues and PRs.

2 . Greet Bot [Integration](https://github.com/actions/first-interaction)
* Greet First Time Contributors

3 . Request - Info [Integration](https://github.com/apps/request-info)
* Request for the information if the issues/PR Content body is empty
*  Help us in Spam / invalid issues and PRs

cc @joewxboy 

Fixes #138 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Ayush7614** [comment]
Cc @joewxboy 👀

**Comment by Sukriti-sood** [comment]
@Ayush7614  Please place config.yml file in .github folder . Remove greetings.yml as config.yml is doing some work for welcoming new user. and According to me, this repository doesn't need Stale Bot (It closes the issue and mark them as stale , if there will not activity) as This repository has issues which are created more than a year before.

**Review by Abhijay007 — COMMENTED** [review]
@Ayush7614  DCO sign is missing that's why tests are falling.

**Comment by Ayush7614** [comment]
> @Ayush7614 Take a look at https://github.com/open-horizon/open-horizon.github.io/pull/145/checks?check_run_id=5222680381
> 
> At the bottom of the page, it shows you a specific commit that is missing a sign-off. If you amend that commit to add the sign-off, that will unblock us from merging.

image
@joewxboy @Abhijay007 this error is coming how can i solve this?

**Pull request closed without merging**
