### PR TITLE
Issue-233: Added MAINTAINERS.md file

### LINKED ISSUE #233: Add MAINTAINERS.md file to the repo
In the root of the repository, create a MAINTAINERS.md file.  This file will contain all of the Maintainers from the repo's owning Working Group.  The format will be as follows:

Repository Maintainers
=================

See the information about [community membership roles](https://wiki.lfedge.org/display/OH/Community+Membership) to learn about the role of the maintainers and the process to become one.

| Name | GitHub | email
|------|--------|------|----------------------
| Joe Pearson | joewxboy | <joe.pearson@us.ibm.com>

### PR DESCRIPTION
**Pull request by joewxboy**
# Pull Request Template

## Description

Added a bare-bones file to start with.

Fixes #233 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

@johnwalicki Please review.

### CODE REVIEW

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
@joewxboy  the table is not displaying correctly 

image

**Comment by joewxboy** [comment]
> @joewxboy the table is not displaying correctly
> 
> image

I believe that's an artifact of GitHub's preview function since it's prefixing each line with an indent due to the diff.  If you checkout the branch and preview the file locally, it appears fine:

Screen Shot 2022-04-21 at 1 49 21 PM

**Review by Abhijay007 — COMMENTED** [review]
@joewxboy I tried this by committing the change in of my repos but is not displayed in tabular form. 

image

Repository Maintainers
======================

See the information about [community membership roles](https://wiki.lfedge.org/display/OH/Community+Membership) to learn about the role of the maintainers and the process to become one.

| Name | GitHub | email
|--------|--------|--------|
| Joe Pearson | joewxboy | <joe.pearson@us.ibm.com>

in order to display this in the tabular form you just need to remove the last line from the table

to be specific this line :

image

**Comment by joewxboy** [comment]
@Abhijay007 I wonder if what you're seeing is an artifact of the line endings being different on a Windows system vs macOS and Linux.  Out of curiosity, what would MAINTAINERS.md look like if you built the site.  I'm assuming that GitHub pages would turn it into MAINTAINERS.html and we would see an HTML table.  Could you try that on your computer and I'll try it on mine.

**Comment by joewxboy** [comment]
> @Abhijay007 I wonder if what you're seeing is an artifact of the line endings being different on a Windows system vs macOS and Linux. Out of curiosity, what would MAINTAINERS.md look like if you built the site. I'm assuming that GitHub pages would turn it into MAINTAINERS.html and we would see an HTML table. Could you try that on your computer and I'll try it on mine.

Confirmed on my computer.  How about yours?

Screen Shot 2022-04-21 at 7 34 26 PM

**Comment by Abhijay007** [comment]
> > @Abhijay007 I wonder if what you're seeing is an artifact of the line endings being different on a Windows system vs macOS and Linux. Out of curiosity, what would MAINTAINERS.md look like if you built the site. I'm assuming that GitHub pages would turn it into MAINTAINERS.html and we would see an HTML table. Could you try that on your computer and I'll try it on mine.
> 
> Confirmed on my computer. How about yours?
> 
> Screen Shot 2022-04-21 at 7 34 26 PM

ya same here : 
image

**Comment by joewxboy** [comment]
> > > @Abhijay007 I wonder if what you're seeing is an artifact of the line endings being different on a Windows system vs macOS and Linux. Out of curiosity, what would MAINTAINERS.md look like if you built the site. I'm assuming that GitHub pages would turn it into MAINTAINERS.html and we would see an HTML table. Could you try that on your computer and I'll try it on mine.
> > 
> > 
> > Confirmed on my computer. How about yours?
> > Screen Shot 2022-04-21 at 7 34 26 PM
> 
> ya same here : image

OK, thanks.  I'll assume my theory about the macOS versus Windows line endings is correct.  One way to confirm is to use an editor on Windows that understands Unix line endings like Visual Studio Code.  If it can open the MAINTAINERS.md file and see the table on three lines that clinches the issue.

**Review by Abhijay007 — COMMENTED** [review]
results form VS code : 
 
image

**Comment by joewxboy** [comment]
Excellent.  Here's [the takeaway](https://www.stevenchang.tw/blog/2019/12/26/How-to-convert-newline-LF-CRLF):

"DOS/Windows newline(CRLF) and Unix format(LF)

The term CRLF refers to Carriage Return (ASCII 13, \r) Line Feed(ASCII 10, \n).

They’re used to note the termination of a line, however, dealt with differently in today’s popular Operation Systems.

For example: in Windows, both a CR and LF are required to note the end of a line, whereas in Linux/UNIX a LF is only required."  -- from the resource linked above.

**Comment by Abhijay007** [comment]
> 

Thanks for sharing this :)

**Comment by Abhijay007** [comment]
> Excellent. Here's [the takeaway](https://www.stevenchang.tw/blog/2019/12/26/How-to-convert-newline-LF-CRLF):
> 
> "DOS/Windows newline(CRLF) and Unix format(LF)
> 
> The term CRLF refers to Carriage Return (ASCII 13, \r) Line Feed(ASCII 10, \n).
> 
> They’re used to note the termination of a line, however, dealt with differently in today’s popular Operating Systems.
> 
> For example: in Windows, both a CR and LF are required to note the end of a line, whereas in Linux/UNIX a LF is only required." -- from the resource linked above.

Thanks for sharing this :)

**Comment by johnwalicki** [comment]
The world should just drop Windows and standardize on Unix.  Have been stripping out CR from files for 3 decades.

@joewxboy  - @Abhijay007 is correct.  You have an extra `|----------------------`  at L7 of your commit.

**Review by johnwalicki — CHANGES_REQUESTED** [review]
@joewxboy - @Abhijay007 is correct. You have an extra |---------------------- at L7 of your commit.

**Review by Abhijay007 — COMMENTED** [review]
I think you also need to add ending | at the end of dash lines 

like this :  

|--------|--------|--------| 

try the above line ☝️

**Comment by Abhijay007** [comment]
@joewxboy I added line endings in the last commit, now it is in tabular form.

**Review by johnwalicki — APPROVED** [review]
Finally looks good to me

**Review by Abhijay007 — APPROVED** [review]

**Pull request merged**
