### PR TITLE
Add readme

### PR DESCRIPTION
**Pull request by acostry**
This implements issue https://github.com/open-horizon/open-horizon.github.io/issues/4

Signed-off-by: Xiulei Zhu <xiuleizh@cn.ibm.com>

### CODE REVIEW

**Comment by acostry** [comment]
@joewxboy Please help review, thanks.

**Comment by joewxboy** [comment]
@acostry For completeness, did you want to add a small section at the end describing what to do with the forked and cloned repo once the PR has been submitted and approved/merged?  This can be puzzling to some people since they now have the cloned repo on their local filesystem and a forked repo in their github account.  Basically, we may want to tell them how to update their local cloned repo to the upstream master branch, or indicate that it is safe to delete.  Likewise for the forked repo.

**Comment by acostry** [comment]
@joewxboy Good point, I will add this part into the README.

**Comment by acostry** [comment]
@joewxboy added some clean up steps after PR merged.

**Pull request merged**
